# Generated by Django 4.2.19 on 2025-03-16 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face3d', '0002_customuser_username_alter_customuser_face_embedding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
